# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured',
            field=models.ForeignKey(blank=True, help_text='Featured Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='pulse.Media'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='pulse.Media'),
        ),
    ]
