# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('-weight',), 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
    ]
