# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_auto_20171013_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeblock',
            name='context',
            field=models.TextField(blank=True, default='{}', verbose_name='Context'),
        ),
    ]
