# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import replica.pulse.models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='channel',
            field=models.ForeignKey(default=replica.pulse.models.DefaultChannel, on_delete=django.db.models.deletion.CASCADE, to='pulse.Channel', verbose_name='Entry Type'),
        ),
    ]
