# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0004_auto_20170308_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'title', 'ordering': ['-title'], 'verbose_name_plural': 'topics'},
        ),
        migrations.AlterField(
            model_name='draft',
            name='body_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='draft',
            name='deck_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
