# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_auto_20170311_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, help_text='Site Description', null=True),
        ),
    ]
