# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0007_auto_20170406_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='slug',
            field=models.SlugField(max_length=510, unique_for_date='pub_date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.CharField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='slug',
            field=models.SlugField(max_length=510),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=510),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=510),
        ),
    ]
