# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import replica.pulse.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pulse', '0008_auto_20170406_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=510)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('template_html', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HTML Template',
                'ordering': ('-date_updated',),
                'get_latest_by': 'date_updated',
                'db_table': 'r_EntryTemplate',
                'verbose_name_plural': 'HTML Templates',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('weight',), 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='draft',
            name='channel',
            field=models.ForeignKey(default=replica.pulse.models.DefaultChannel, on_delete=django.db.models.deletion.CASCADE, to='pulse.Channel', verbose_name='Entry Type'),
        ),
        migrations.AddField(
            model_name='entry',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.EntryTemplate'),
        ),
    ]
