# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0009_auto_20170502_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
