# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0010_auto_20170603_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='summary_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
