# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0012_media_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='summary_rendered',
            new_name='summary_html',
        ),
    ]
