# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import replica.pulse.models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0014_sitesettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'embed'), (1, 'image'), (2, 'url'), (3, 'Instagram')], default=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, help_text='Support for PNG, JPG, GIF only', max_length=510, upload_to=replica.pulse.models.upload_media),
        ),
    ]
