# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import replica.pulse.models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0015_auto_20170923_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, max_length=510, upload_to=replica.pulse.models.upload_media_md),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail_small',
            field=models.ImageField(blank=True, max_length=510, upload_to=replica.pulse.models.upload_media_sm),
        ),
    ]
