# Generated by Django 2.0 on 2018-04-22 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import replica.pulse.models
import replica.pulse.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_codeblock_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='position',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_ptr',
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(default=replica.pulse.utils.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codeblock',
            name='user',
            field=models.ForeignKey(default=replica.pulse.utils.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draft',
            name='channel',
            field=models.ForeignKey(default=replica.pulse.models.DefaultChannel, on_delete=django.db.models.deletion.SET_DEFAULT, to='pulse.Channel', verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='user',
            field=models.ForeignKey(default=replica.pulse.utils.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='channel',
            field=models.ForeignKey(default=replica.pulse.models.DefaultChannel, on_delete=django.db.models.deletion.SET_DEFAULT, to='pulse.Channel', verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='featured_image',
            field=models.ForeignKey(blank=True, default=replica.pulse.utils.DefaultUser, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pulse.Media'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='template',
            field=models.ForeignKey(blank=True, default=replica.pulse.utils.DefaultUser, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pulse.CodeBlock'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=replica.pulse.utils.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrylink',
            name='entry',
            field=models.ForeignKey(default=replica.pulse.models.DefaultEntry, on_delete=django.db.models.deletion.SET_DEFAULT, to='pulse.Entry'),
        ),
        migrations.AlterField(
            model_name='entrylink',
            name='user',
            field=models.ForeignKey(default=replica.pulse.utils.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(default=replica.pulse.utils.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse.Media'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=replica.pulse.utils.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuPosition',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
