# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulse.Media')),
                ('instagram_id', models.CharField(max_length=510, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Instagram Media',
                'db_table': 'r_instagram',
            },
            bases=('pulse.media',),
        ),
    ]
