# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import replica.contrib.insta.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagram',
            options={'verbose_name_plural': 'Instagram Media'},
        ),
        migrations.AddField(
            model_name='instagram',
            name='instagram_image',
            field=models.ImageField(blank=True, help_text='Support for PNG, JPG, GIF only', upload_to=replica.contrib.insta.models.upload_media),
        ),
    ]
