# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20170923_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='instagram_image',
        ),
    ]
