# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitelink',
            name='note_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
