# Generated by Django 2.0 on 2018-04-22 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import replica.contrib.redirection.models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0002_auto_20170923_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelink',
            name='user',
            field=models.ForeignKey(default=replica.contrib.redirection.models.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
