# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('body_html', models.TextField(editable=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date posted')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False, help_text='Should be checked if no one else should see this.')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'db_table': 'r_Note',
                'ordering': ('-pub_date',),
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('deck', models.TextField(blank=True, verbose_name='deck')),
                ('deck_html', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Should be checked you want anyone to see')),
                ('rev_order', models.BooleanField(default=False, help_text='Reverse order of list displayed? (Newest on top)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Timelines',
                'db_table': 'r_Timeline',
                'ordering': ('-date_created',),
                'get_latest_by': 'date_created',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micro.Timeline'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together=set([('slug', 'user')]),
        ),
    ]
