# Generated by Django 2.0 on 2018-04-22 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import replica.contrib.micro.models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='micro.Timeline'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=replica.contrib.micro.models.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(default=replica.contrib.micro.models.DefaultUser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='timelines', to=settings.AUTH_USER_MODEL),
        ),
    ]
