# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 01:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0006_sitesettings_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('deck', models.TextField(blank=True, max_length=1020)),
                ('deck_html', models.TextField(blank=True, editable=False)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Publication date')),
                ('entries', models.ManyToManyField(blank=True, db_table='r_Collection_Entries', to='pulse.Entry')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'r_Collection',
                'get_latest_by': 'pub_date',
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'Collection of Entries',
            },
        ),
    ]
