# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name_plural': 'Collections'},
        ),
    ]
